type Mutation{
    saveBook(book:BookInput) : Book
    updateBookByID(bookID:ID!,updateBookInput:UpdateBookInput): Book
}

type Query {

    books: [Book]
    bookByID(bookID: Int) : Book
    author(book:BookInput):Author
}


type Book {
    bookID: ID
    bookName: String,
    pageCount: Int
    author : Author
}

type Author{
    authorID : ID
    authorName : String
}

input BookInput {
    bookID: ID
    bookName: String
    pageCount: Int
    author: authorInput
}

input authorInput{
    authorID : ID
    authorName : String
}


input UpdateBookInput {
    bookName: String
    pageCount: Int
}
